### ISSUE TITLE
Give credit where credit is due

### ISSUE THREAD

**Issue by atuttle** [cfmaniac/CF-CertMan#1]
I see that after taking down your entire website, twitter account, and github account when you were found out and exposed for being a systematic plagiarizer of epic proportions you are back and you've decided to completely scrub the git history of repos that have been around for quite a long time. **I was using CertMan 5+ years ago but your first commit was 2 hours ago.** Do you have any idea how fishy that looks?

"I made this! But I'm not going to let you see the history" (because I probably did something I don't want anyone to see...)

It appears you were added to Paul Connell's CertMan project some time around March 2013:

http://web.archive.org/web/20130302152824/http://certman.riaforge.org/

I imagine Paul has moved on and gave you permission to continue its maintenance; and that's a very normal and regular thing to happen in Open Source Software. And it appears that at least this time you've left some trace of his history with the project intact: (good for you!)

https://github.com/webdevsourcerer/CF-CertMan/blob/master/CF7-8-9/index.cfm#L1

Overall things aren't _toooo_ fishy with this repo, but it would be considered good form to have a note somewhere in the readme giving credit to Paul as the original author and describing yourself as the current maintainer.

**Comment by webdevsourcerer** [comment]
I took over the Project when Paul decided to not Support it anymore, and I still maintain it.

**Comment by atuttle** [comment]
Just leaving a reference here for the record. Looks like you resolved this with the following commit: 6daf5a8a20
