### ISSUE TITLE
Error imported cert in ColdFusion 11

### ISSUE THREAD

**Issue by fractorr** [cfmaniac/CF-CertMan#3]
I just installed the ColdFusion 10 version in ColdFusion 11 and tried to import a certificate and got this error.

 Variable KEYCLASHALIAS is undefined.

The error occurred in C:/ColdFusion11/cfusion/wwwroot/CFIDE/administrator/certman/addCert.cfm: line 40

```
38 : </cftry>
39 : 
40 : <cfif Len(Trim(KeyClashAlias))>
41 :    <cfif FileExists("#cffile.serverdirectory#/#cffile.serverfile#")>
42 :        <cffile action="Delete" file="#cffile.serverdirectory#/#cffile.serverfile#">
```

Resources:

```
Check the ColdFusion documentation to verify that you are using the correct syntax.
Search the Knowledge Base to find a solution to your problem.
```

Browser     Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
Remote Address      127.0.0.1
Referrer    http://127.0.0.1/CFIDE/administrator/certman/addCertForm.cfm?addCert=Add+a+New+Certificate
Date/Time       17-Sep-15 07:28 PM
Stack Trace
at cfaddCert2ecfm16506593.runPage(C:/ColdFusion11/cfusion/wwwroot/CFIDE/administrator/certman/addCert.cfm:40)

**Comment by cfmaniac** [comment]
There are 1 of 2 Reasons this is happening:
- You may be using a self-signed certificate
  ---OR---
- Your Java /lib/security/ maybe emply (in your core Java Installation, not your CF Install java).

Please check those and let me know.

**Comment by redhot2323** [comment]
We had the same problem in Variable KEYCLASHALIAS is undefined. we have successfully fixed this using the keytool
