### ISSUE TITLE
The getCommonName method was not found

### ISSUE THREAD

**Issue by pvandermn** [cfmaniac/CF-CertMan#5]
In opening the Certificate Management screen on one of our servers, I get the error "The getCommonName method was not found."  Any thoughts for resolving this?

Either there are no methods with the specified method name and argument types or the getCommonName method is overloaded with argument types that ColdFusion cannot decipher reliably. ColdFusion found 0 methods that match the provided arguments. If this is a Java object and you verified that the method exists, use the javacast function to reduce ambiguity.
--
The error occurred in C:/ColdFusion11/cfusion/wwwroot/CFIDE/administrator/certman/Certificate.cfc: line 19

17 : 	 
18 : 	<cffunction name="getCommonName" output="false"> 
19 : 		<cfif Len(Trim(Variables.ThisCertificate.getSubjectDN().getCommonName()))> 
20 : 			<cfreturn Variables.ThisCertificate.getSubjectDN().getCommonName()> 
21 : 		<cfelse>

**Comment by tommyready** [comment]
When you dump out the structure is the method there?

**Comment by pvandermn** [comment]
Thank you for your quick response, and sorry for my late reply.  No, when I dump Variables.ThisCertificate, the getSubjectDN method exists, but getCommonName is not within it.  This is a dump of getSubjectDN.

![image](https://user-images.githubusercontent.com/2575225/28569695-93d8e828-7100-11e7-81e9-47fb1a2d5943.png)

**Comment by pvandermn** [comment]
I resolved this by simply copying the certman folder from another server where it was working.  All fine now.
